io:
  production:
    photons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      infile: /eos/user/b/bfontana/FPGAs/new_algos/photons_0PU_bc_stc_hadd.root
      outfile: skim_photons_default.root
    electrons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      infile: /eos/user/b/bfontana/FPGAs/new_algos/electrons_hadd.root
      outfile: /eos/user/b/bfontana/FPGAs/new_algos/skim_electrons_default.root
    pions:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      infile: /eos/user/b/bfontana/FPGAs/new_algos/pions_hadd.root
      outfile: /eos/user/b/bfontana/FPGAs/new_algos/skim_pions_default.root
  PU0:
    photons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      file: /data_CMS/cms/alves/L1HGCAL/skim_with_pt_ntuple_1.root #/data_CMS/cms/ehle/L1HGCAL/PU0/photons/skims/skim_tightTC_dRxy_fullEta_photons_0PU_bc_stc_hadd.root
    electrons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      file: /eos/user/i/iehle/data/PU0/photons/skim_photons_0PU_bc_stc_hadd.root #/data_CMS/cms/ehle/L1HGCAL/PU0/electrons/skims/skim_tightTC_dRxy_fullEta_electrons_0PU_bc_stc_hadd.root
    pions:
      dir: hgcalTriggerNtuplizer
      tree: HGCalTriggerNtuple
      file: /data_CMS/cms/ehle/L1HGCAL/PU0/pions/skims/skim_tightTC_dRxy_fullEta_new_pions_0PU_bc_stc_hadd.root
  PU200:
    photons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      file: /eos/user/m/mchiusi/visualization/display3d/skim_photons_hadd_200PU.root #/data_CMS/cms/ehle/L1HGCAL/PU200/photons/skims/skim_tightTC_dRxy_fullEta_photons_200PU_bc_stc_hadd.root
    electrons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      file: /data_CMS/cms/ehle/L1HGCAL/PU200/electrons/skims/skim_tightTC_dRxy_fullEta_electrons_200PU_bc_stc_hadd.root
    pions:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      file: /data_CMS/cms/ehle/L1HGCAL/PU200/pions/skims/skim_tightTC_dRxy_fullEta_pions_200PU_bc_stc_hadd.root

geometry:
    dir: L1THGCaltriggergeomtester
    tree: TreeTriggerCells
    file: /data_CMS/cms/alves/L1HGCAL/test_triggergeom_12_5_2_patch1_FIXED_v2.root
    waferSize: 16.64408
    sensorSeparation: 0.1
    nlayersCEE: 28
    nlayersCEH: 22
  
selection:
    particles: photons
    disconnectedTriggerLayers: [2,4,6,8,10,12,14,16,18,20,22,24,26,28]
    reachedEE: 2
    deltarThreshold: 0.05
    mipThreshold: 0.5

defaultEvents:
    PU0:
      photons: [170032, 170044]
      electrons: [92243, 92244]
      pions: [9102, 9148]
    PU200:
      photons: [62878, 55896]

varEvents:
  gen:
    event: 'event'
    geta: 'good_genpart_exeta'
    gphi: 'good_genpart_exphi'
    gen: 'good_genpart_energy'
    gpt: 'good_genpart_pt'
  tc:
    event: 'event'
    wu: 'good_tc_waferu'
    wv: 'good_tc_waferv'
    l:  'good_tc_layer'
    cv: 'good_tc_cellu'
    cu: 'good_tc_cellv'
    x: 'good_tc_x'
    y: 'good_tc_y'
    z: 'good_tc_z'
    phi: 'good_tc_phi'
    eta: 'good_tc_eta'
    #idcl: 'good_tc_multicluster_id'
    pt: 'good_tc_pt'
    en: 'good_tc_mipPt'
    en_gev: 'good_tc_energy'
  # tsum:
  #   event: 'event'
  #   wu: 'good_ts_waferu'
  #   wv: 'good_ts_waferv'
  #   l:  'good_ts_layer'
  #   en: 'good_ts_mipPt'
  cl:
    event: 'event'
    eta: 'good_cl3d_eta'
    phi: 'good_cl3d_phi'
    en: 'good_cl3d_energy'
    pt: 'good_cl3d_pt'
    id: 'good_cl3d_id'
    # matches: 'matches'
    # dR: 'deltaR'
    
varGeometry:
    wu: 'waferu'
    wv: 'waferv'
    l: 'layer'
    cu: 'triggercellu'
    cv: 'triggercellv'
    ieta: 'triggercellieta'
    iphi: 'triggercelliphi'
    x: 'x'
    y: 'y'
    z: 'z'
    side: 'zside'
    subd: 'subdet'
    wvs: 'waferv_shift'
    c: 'color'
    orient: 'waferorient'
    part: 'waferpart'

3Ddisplay:
  PU0:
    photons: 'photons_0PU_cluster.hdf5'
    electrons: 'electrons_0PU_cluster.hdf5'
    pions: 'pions_0PU_cluster.hdf5'
  PU200:
    photons: 'photons_200PU_cluster.hdf5'
    electrons: 'electrons_200PU_cluster.hdf5'
    pions: 'pions_200PU_cluster.hdf5'
  reprocess: False
  coefs: [0.006,0.010,0.014,0.018,0.022,0.026,0.030]

clusterStudies:
  local: True
  localDir: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/
  ehleDir: /eos/user/i/iehle/
  dataFolder: data/
  pileup: False
  reprocess: True # {True: Process the ROOT file, False: read the .parquet if already processed}
  reinit: True # Run Fill, Smooth, Seed steps
  parquetTag: fullEta_MarcoEffTest
  clusterSizeBaseName: cluster_size_funRadiiTest
  coeffs: [0.0, 0.05, 50]
  nevents: -1
  tree: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple/HGCalTriggerNtuple
  combination:
    PU0:
      photons:
        sub_dir: photons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/negEta/smooth/
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth
      electrons:
        sub_dir: electrons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/negEta/smooth/
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth
      pions:
        sub_dir: pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/negEta/bc_stc
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc
    PU200:
      photons:
        sub_dir: photons/cluster/weighted/selectOneStd/maxSeed/negEta/smooth
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed
      electrons:
        sub_dir: electrons/cluster/weighted/selectOneStd/maxSeed/posEta/smooth
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed
      pions:
        sub_dir: pions/cluster/weighted/selectOneStd/maxSeed/smooth/bc_stc/negEta
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed
  dashApp:
    local:
      PU0:       
        photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/posEta/bc_stc/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc_ThresholdDummyHistomaxnoareath20_filtered_fullEta_enCalibrated.hdf5
        pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/posEta/bc_stc/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc_ThresholdDummyHistomaxnoareath20_filtered_fullEta_enCalibrated_byNorm.hdf5
      PU200:
        photons: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        electrons: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        #pions: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/smooth/bc_stc/posEta/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_en_eta_calibrated.hdf5
        pions: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/smooth/bc_stc/posEta/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_en_eta_calibrated_byNorm.hdf5
    EOS:
      PU0:
        photons: /eos/user/i/iehle/data/PU0/photons/weighted/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        electrons: /eos/user/i/iehle/data/PU0/electrons/weighted/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        pions: /eos/user/i/iehle/data/PU0/pions/weighted/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      PU200:
        photons: /eos/user/i/iehle/data/PU200/photons/weighted/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        electrons: /eos/user/i/iehle/data/PU200/electrons/weighted/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
        pions: /eos/user/i/iehle/data/PU200/pions/weighted/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_lessCols.hdf5
  optimization:
    PU0:
      photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/photons_PU0_cluster_size_ThresholdDummyHistomaxnoareath20.hdf5
      electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/cluster_size_ThresholdDummyHistomaxnoareath20.hdf5
      pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/posEta/bc_stc/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
    PU200:
      photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/negEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/weighted/selectOneStd/maxSeed/negEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      pions: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/smooth/bc_stc/posEta/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      weights:
        photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/posEta/smooth/etaCorr.hdf5
        pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/smooth/bc_stc/posEta/etaCorr_fromCenter.hdf5
    baseName: optimization_selectOneEffRms_maxSeed
    pt_cut: 5
    cl_pt_cut: 3
    eta_min: 1.6
    eta_max: 2.9

base:
  NbinsRz: 42
  NbinsPhi: 216
  MinROverZ: 0.076
  MaxROverZ: 0.58
  MinPhi: -3.14159
  MaxPhi: +3.14159
  EtaMin: 1.7
  EtaMax: 2.8
  EtaMinStrict: 2.0
  EtaMaxStrict: 2.6
  EnResSplits: -0.35
  EnResNoSplits: -0.2
  FesAlgo: 'ThresholdDummyHistomaxnoareath20'

fill:
  FillOut: 'fill'
  FillOutGenCl: 'fill_gencl'
  FillOutTcAll: 'fill_all'

smooth:
  # copied from L1Trigger/L1THGCal/python/hgcalBackEndLayer2Producer_cfi.py
  BinSums: [13, 11, 11, 11, 9, 9, 9, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  SeedsNormByArea: False
  AreaPerTriggerCell: 4.91E-05
  SmoothIn: 'fill'
  SmoothOut: 'smooth'

seed:
  SeedIn: 'smooth'
  SeedOut: 'seed'
  histoThreshold: 20.

cluster:
    ClusterInTC: 'fill'
    ClusterInTCCS: 'csall'
    ClusterInTCCSCylinder: 'cscylinder'
    CSCylinder: False
    ClusterInSeeds: 'seed'
    ClusterInSeedsCS: 'seed_cs'
    ClusterOutPlot: 'cluster_plot'
    ClusterOutValidation: 'cluster_valid'
    ClusterOutPlotCS: 'cluster_plot_cs'
    ClusterOutValidationCS: 'cluster_valid_cs'
    CoeffA: [
    0.015, 0.015, 0.015, 0.015, 0.015, 0.015, 0.015,
    0.020, 0.020, 0.020, 0.020, 0.020, 0.020, 0.020,
    0.030, 0.030, 0.030, 0.030, 0.030, 0.030, 0.030,
    0.040, 0.040, 0.040, 0.040, 0.040, 0.040, 0.040, #EM
    0.040, 0.040, 0.040, 0.040, 0.040, 0.040,
    0.050, 0.050, 0.050, 0.050, 0.050, 0.050, # FH
    0.050, 0.050, 0.050, 0.050, 0.050, 0.050,
    0.050, 0.050, 0.050, 0.050, 0.050, 0.050] # BH
    CoeffB: 0
    MidRadius: 2.3
    PtC3dThreshold: 0.5
  
valid:
  ClusterOutValidation: 'cluster_valid'
  FillOutGenCl: 'fill_gencl'
  FillOut: 'fill'
  FillOutTcAll: 'fill_all'

valid_cluster:
  ClusterOutValidation: 'cluster_valid_cs'
  CSclOut: 'cs3d'
  CSgenOut: 'csgen'
  CStcOut: 'csall'
  CSregionOut: 'cscylinder'
  tcDeltaRthresh: [] #[0.1, 0.5]

valid_seed_cs:
  CSclOut: 'cs3d'
  CSgenOut: 'csgen'
  CStcOut: 'cstc'
  SeedOut: 'seed_cs'

valid_seed_default:
  SeedOut: 'seed'

optimization:
  Epochs: 99999
  KernelSize: 10
  WindowSize: 3
  OptIn: 'triggergeom_condensed'
  OptEnResOut: 'opt_enres'
  OptPosResOut: 'opt_posres'
  OptCSVOut: 'stats'
  FillOutTcAll: 'fill_all'

cs:
  CSclOut: 'cs3d'
  CSgenOut: 'csgen'
  CStcOut: 'cstc'
  CStcAllOut: 'csall'
  NoCStcOut: 'nocs'
  CScylinderOut: 'cscylinder'
  
seed_cs:
  InputName: CStcOut #NoCStcOut default is to consider the CS
  SeedOut: 'seed_cs'
  histoThreshold: 20.
  hexDist: True
