io:
  PU0:
    photons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      #file: /data_CMS/cms/ehle/L1HGCAL/PU0/photons/skims/skim_tightTC_dRxy_hadd.root
      file: /data_CMS/cms/ehle/L1HGCAL/PU0/photons/skims/skim_tightTC_dRxy_fullEta_photons_0PU_bc_stc_hadd.root
    electrons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      #file: /data_CMS/cms/ehle/L1HGCAL/PU0/electrons/skims/skim_tightTC_dRxy_hadd.root
      file: /data_CMS/cms/ehle/L1HGCAL/PU0/electrons/skims/skim_tightTC_dRxy_fullEta_electrons_0PU_bc_stc_hadd.root
    pions:
      dir: hgcalTriggerNtuplizer
      #dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      #file: /data_CMS/cms/ehle/L1HGCAL/PU0/pions/skims/skim_tightTC_dRxy_hadd.root
      #file: /data_CMS/cms/ehle/L1HGCAL/PU0/pions/skims/skim_tightTC_dRxy_fullEta_pions_0PU_bc_stc_hadd.root # FAKE: THIS IS ACTUALLY 200PU !!
      file: /data_CMS/cms/ehle/L1HGCAL/PU0/pions/skims/skim_tightTC_dRxy_fullEta_new_pions_0PU_bc_stc_hadd.root
  PU200:
    photons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      #file: /data_CMS/cms/ehle/L1HGCAL/PU200/photons/skims/skim_tightTC_dRxy_hadd.root
      file: /data_CMS/cms/ehle/L1HGCAL/PU200/photons/skims/skim_tightTC_dRxy_fullEta_photons_200PU_bc_stc_hadd.root
    electrons:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      #file: /data_CMS/cms/ehle/L1HGCAL/PU200/electrons/skims/skim_tightTC_dRxy_hadd.root
      file: /data_CMS/cms/ehle/L1HGCAL/PU200/electrons/skims/skim_tightTC_dRxy_fullEta_electrons_200PU_bc_stc_hadd.root
    pions:
      dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
      tree: HGCalTriggerNtuple
      #file: /data_CMS/cms/ehle/L1HGCAL/PU200/pions/skims/skim_tightTC_dRxy_hadd.root
      file: /data_CMS/cms/ehle/L1HGCAL/PU200/pions/skims/skim_tightTC_dRxy_fullEta_pions_200PU_bc_stc_hadd.root

geometry:
    dir: L1THGCaltriggergeomtester
    tree: TreeTriggerCells
    file: /data_CMS/cms/alves/L1HGCAL/test_triggergeom_12_5_2_patch1_FIXED_v2.root
    waferSize: 16.64408
    sensorSeparation: 0.1
    nlayersCEE: 28
    nlayersCEH: 22
  
selection:
    particles: photons
    pileup: True
    disconnectedTriggerLayers: [2,4,6,8,10,12,14,16,18,20,22,24,26,28]
    reachedEE: 2
    deltarThreshold: 0.05
    mipThreshold: 0.5

defaultEvents:
    photons: [170032, 170044]
    electrons: [92243, 92244]
    pions: [9102, 9148]

skim:
  #inDir: /data_CMS/cms/alves/L1HGCAL/
  inDir: /data_CMS/cms/ehle/L1HGCAL/PU0/
  outDir: /data_CMS/cms/ehle/L1HGCAL/PU0/
  #rootDir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
  rootDir: hgcalTriggerNtuplizer
  tree: HGCalTriggerNtuple
  outfileBaseName: tightTC_dRxy_fullEta_TEST
  tcDeltaRThresh: 0.1

job:
  user: iehle
  proxy: ~/.t3/proxy.cert
  queue: short
  local: False
  #script: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/bye_splits/production/submit_scripts/calibrate_cluster_energy.sh
  #arguments: [filename, particles]
  script: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/bye_splits/production/submit_scripts/condor_cluster_size.sh
  arguments: [filename, particles, pileup]
  read_dir: False # {True: read arguments as paths in <submit_dir>/ntuples, False: read arguments stored on the .txt <files>}
  photons:
    submit_dir: /data_CMS/cms/ehle/L1HGCAL/PU0/photons/
    files: /data_CMS/cms/ehle/L1HGCAL/PU200/coefs.txt
    files_per_batch: 1
  electrons:
    submit_dir: /data_CMS/cms/ehle/L1HGCAL/PU0/electrons/
    files: /data_CMS/cms/ehle/L1HGCAL/PU200/coefs.txt
    files_per_batch: 1
  pions:
    submit_dir: /data_CMS/cms/ehle/L1HGCAL/PU0/pions/
    files: /data_CMS/cms/ehle/L1HGCAL/PU200/coefs.txt
    files_per_batch: 1

varEvents:
  gen:
    event: 'event'
    geta: 'good_genpart_exeta'
    gphi: 'good_genpart_exphi'
    gen: 'good_genpart_energy'
    gpid: 'good_genpart_pid'
  tc:
    event: 'event'
    wu: 'good_tc_waferu'
    wv: 'good_tc_waferv'
    l:  'good_tc_layer'
    cv: 'good_tc_cellu'
    cu: 'good_tc_cellv'
    x: 'good_tc_x'
    y: 'good_tc_y'
    z: 'good_tc_z'
    phi: 'good_tc_phi'
    eta: 'good_tc_eta'
    idcl: 'good_tc_multicluster_id'
    pt: 'good_tc_pt'
    en: 'good_tc_mipPt'
    en_gev: 'good_tc_energy'
  #tsum:
    #event: 'event'
    #wu: 'good_ts_waferu'
    #wv: 'good_ts_waferv'
    #l:  'good_ts_layer'
    #en: 'good_ts_mipPt'
  cl:
    event: 'event'
    eta: 'good_cl3d_eta'
    phi: 'good_cl3d_phi'
    en: 'good_cl3d_energy'
    id: 'good_cl3d_id'
    matches: 'matches'
    dR: 'deltaR'
    #layer: 'good_cl3d_firstlayer'

varGeometry:
    wu: 'waferu'
    wv: 'waferv'
    l: 'layer'
    cu: 'triggercellu'
    cv: 'triggercellv'
    ieta: 'triggercellieta'
    iphi: 'triggercelliphi'
    x: 'x'
    y: 'y'
    z: 'z'
    side: 'zside'
    subd: 'subdet'
    wvs: 'waferv_shift'
    c: 'color'
    orient: 'waferorient'
    part: 'waferpart'

clusterStudies:
  local: True
  localDir: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/
  ehleDir: /eos/user/i/iehle/
  dataFolder: data/
  pileup: True
  reprocess: True # {True: Process the ROOT file, False: read the .parquet if already processed}
  parquetTag: fullEta_smoothTest
  #clusterSizeBaseName: cluster_size_weighted_selectOneEffRms_maxSeed
  #clusterSizeBaseName: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth
  clusterSizeBaseName: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc
  coeffs: [0.0, 0.05, 50]
  nevents: -1
  tree: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple/HGCalTriggerNtuple
  local: False
  combination:
    PU0:
      photons:
        #sub_dir: photons/cluster/weighted/final/selectOnestd/maxSeed
        #sub_dir: photons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/negEta/transvSize
        sub_dir: photons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/negEta/smooth/
        #basename: cluster_size_transvSize
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth
      electrons:
        #sub_dir: electrons/cluster/weighted/final/selectOnestd/maxSeed/photWeights
        #sub_dir: electrons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/negEta #REMEMBER THAT THIS IS STILL PHOT WEIGHTED
        sub_dir: electrons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/negEta/smooth/
        #basename: cluster_size_weighted_selectOneEffRms_maxSeed
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth
      pions:
        #sub_dir: pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/negEta/
        #sub_dir: pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/negEta/smooth/
        #sub_dir: pions/cluster/bc_stc/negEta/
        sub_dir: pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/negEta/bc_stc
        #basename: cluster_size_weighted_selectOneEffRms_maxSeed #STILL BOUND 5
        #basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc
    PU200:
      photons:
        #sub_dir: photons/cluster/weighted/selectOneStd/maxSeed
        #basename: cluster_size_weighted_selectOneStd_bound5_maxSeed
        sub_dir: photons/cluster/weighted/selectOneStd/maxSeed/negEta/smooth
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed
      electrons:
        #sub_dir: electrons/cluster/weighted/selectOneStd/maxSeed/photWeights
        #basename: cluster_size_photWeighted_selectOneEffRms_maxSeed
        sub_dir: electrons/cluster/weighted/selectOneStd/maxSeed/posEta/smooth
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed
      pions:
        sub_dir: pions/cluster/weighted/selectOneStd/maxSeed/negEta/smooth
        basename: cluster_size_fullEta_weighted_selectOneEffRms_maxSeed
  dashApp:
    PU0:       
      #photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/weighted/final/selectOnestd/maxSeed/cluster_size_weighted_selectOneStd_adjustMaxWeight_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/weighted/final/selectOnestd/maxSeed/cluster_size_weighted_selectOneStd_adjustMaxWeight_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/weighted/final/selectOnestd/maxSeed/photWeights/cluster_size_photWeighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/weighted/final/selectOnestd/maxSeed/fullEta/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/cluster_size_weighted_selectOneStd_bound5_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/weighted/final/bound5/selectOneStd/maxSeed/fullEta/posEta/bc_stc/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_smooth_bc_stc_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
    PU200:
      #photons: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/cluster_size_weighted_selectOneStd_bound5_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      photons: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/fullEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/weighted/selectOneStd/maxSeed/cluster_size_weighted_selectOneStd_bound5_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/weighted/selectOneStd/maxSeed/photWeights/cluster_size_photWeighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #electrons: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/weighted/selectOneStd/maxSeed/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      electrons: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/weighted/selectOneStd/maxSeed/fullEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/cluster_size_weighted_selectOneStd_bound5_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      pions: /grid_mnt/vol_home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/smooth/cluster_size_fullEta_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
      #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/fullEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered_fullEta.hdf5
  optimization:
    PU0:
      photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/photons_PU0_cluster_size_ThresholdDummyHistomaxnoareath20.hdf5
      electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/cluster_size_ThresholdDummyHistomaxnoareath20.hdf5
      pions: data/new_algos/PU0/pions/cluster/fullEvents/cluster_size_eventTest_ThresholdDummyHistomaxnoareath20.hdf5
    PU200:
      photons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/weighted/selectOneStd/maxSeed/negEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      electrons: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/weighted/selectOneStd/maxSeed/negEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
      #pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/posEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20.hdf5
      pions: /home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/pions/cluster/weighted/selectOneStd/maxSeed/negEta/cluster_size_weighted_selectOneEffRms_maxSeed_ThresholdDummyHistomaxnoareath20_filtered.hdf5
    baseName: optimization_selectOneEffRms_maxSeed
    pt_cut: 5
    cl_pt_cut: 3
    eta_min: 1.6
    eta_max: 2.9

base:
  NbinsRz: 42
  NbinsPhi: 216
  MinROverZ: 0.076
  MaxROverZ: 0.58
  MinPhi: -3.14159
  MaxPhi: +3.14159
  EtaMin: 1.7
  EtaMax: 2.8
  EtaMinStrict: 2.0
  EtaMaxStrict: 2.6
  EnResSplits: -0.35
  EnResNoSplits: -0.2
  FesAlgo: 'ThresholdDummyHistomaxnoareath20'

fill:
  FillOut: 'fill'
  FillOutComp: 'fill_comp'
  FillOutPlot: 'fill_plot'

smooth:
  # copied from L1Trigger/L1THGCal/python/hgcalBackEndLayer2Producer_cfi.py
  BinSums: [13, 11, 11, 11, 9, 9, 9, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  SeedsNormByArea: False
  AreaPerTriggerCell: 4.91E-05
  SmoothIn: 'fill'
  SmoothOut: 'smooth'

seed:
  SeedIn: 'smooth'
  SeedOut: 'seed'
  histoThreshold: 20.

cluster:
    ClusterInTC: 'fill'
    ClusterInTCROI: 'roiall'
    ClusterInTCROICylinder: 'roicylinder'
    ROICylinder: False
    ClusterInSeeds: 'seed'
    ClusterInSeedsROI: 'seed_roi'
    ClusterOutPlot: 'cluster_plot'
    ClusterOutValidation: 'cluster_valid'
    ClusterOutPlotROI: 'cluster_plot_roi'
    ClusterOutValidationROI: 'cluster_valid_roi'
    CoeffA: [
    0.015, 0.015, 0.015, 0.015, 0.015, 0.015, 0.015,
    0.020, 0.020, 0.020, 0.020, 0.020, 0.020, 0.020,
    0.030, 0.030, 0.030, 0.030, 0.030, 0.030, 0.030,
    0.040, 0.040, 0.040, 0.040, 0.040, 0.040, 0.040, #EM
    0.040, 0.040, 0.040, 0.040, 0.040, 0.040,
    0.050, 0.050, 0.050, 0.050, 0.050, 0.050, # FH
    0.050, 0.050, 0.050, 0.050, 0.050, 0.050,
    0.050, 0.050, 0.050, 0.050, 0.050, 0.050] # BH
    CoeffB: 0
    MidRadius: 2.3
    PtC3dThreshold: 0.5
  
valid:
  ClusterOutValidation: 'cluster_valid'
  FillOutComp: 'fill_comp'
  FillOut: 'fill'

valid_cluster:
  ClusterOutValidation: 'cluster_valid_roi'
  ROIclOut: 'roi3d'
  ROIgenOut: 'roigen'
  ROItcOut: 'roiall'
  ROIregionOut: 'roicylinder'

valid_seed:
  ROIclOut: 'roi3d'
  ROIgenOut: 'roigen'
  ROItcOut: 'roitc'
  SeedOut: 'seed_roi'

optimization:
  Epochs: 99999
  KernelSize: 10
  WindowSize: 3
  OptIn: 'triggergeom_condensed'
  OptEnResOut: 'opt_enres'
  OptPosResOut: 'opt_posres'
  OptCSVOut: 'stats'
  FillOutPlot: 'fill_plot'

roi:
  ROIclOut: 'roi3d'
  ROIgenOut: 'roigen'
  ROItcOut: 'roitc'
  ROItcOut2: 'roiall'
  ROIcylinderOut: 'roicylinder'
  
seed_roi:
  SeedIn: 'roitc'
  SeedOut: 'seed_roi'
  histoThreshold: 20.
  hexDist: True

tcPlot:
  radius: 0.01
  baseName: cluster_size
  plotName: tc_occupancy_new
  PU0:
    photons:
      files: [/home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/photons/cluster/photons_PU0_cluster_size_ThresholdDummyHistomaxnoareath20.hdf5]
      events: []
    electrons:
      files: [/home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/electrons/cluster/cluster_size_ThresholdDummyHistomaxnoareath20.hdf5]
      events: []
    pions:
      files: [/home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU0/pions/cluster/cluster_size_ThresholdDummyHistomaxnoareath20.hdf5]
      events: []
  PU200:
    photons:
      files: [/home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/photons/cluster/cluster_size_ThresholdDummyHistomaxnoareath20.hdf5]
      events: [5284, 183503, 1545]
    electrons:
      files: [/home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/PU200/electrons/cluster/cluster_size_ThresholdDummyHistomaxnoareath20.hdf5]
      events: []    
    pions:
      files: []
      events: []
